# docker-compose.yml
services:
  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    container_name: server
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    ports:
      - "5432:5432"